POST http://localhost:3333/videos
Content-Type: application/json

{
    "title" : "video sobre Node js",
    "description": "este é o primeiro",
    "duration": 180
}

###

GET http://localhost:3333/videos?search=node

###

PUT http://localhost:3333/videos/413d136b-eb48-4019-b8bc-dabdcdbf16b2
Content-Type: application/json

{
    "title" : "video Do Orlando sobre node js",
    "description": "este é o primeiro vídeo do Orlando",
    "duration": 180
}

###

DELETE http://localhost:3333/videos/413d136b-eb48-4019-b8bc-dabdcdbf16b2
